openapi: 3.0.3
x-stoplight:
  id: 16lwreexm90va
info:
  title: Access Token
  description: 'Access Tokens are required to execute all API actions, you can use this resource to obtain one. The authority of the bearer token; the actions it can execute, is determined by the associated Merchant ID, Accounts and Permissions of the app used to create it.'
  contact:
    name: API Integrations
    url: 'https://developer.globalpay.com/?gp-api=true'
    email: api.integrations@globalpay.com
  version: 2021 03 22
servers:
  - url: 'https://apis.sandbox.globalpay.com/ucp'
    description: Sandbox Environment
  - url: 'https://apis.globalpay.com/ucp'
    description: Production Environment
tags:
  - name: Create Access Token
    description: Authenticate using app credentials to use GP API.
    externalDocs:
      url: 'https://developer.globalpay.com/authentication'
paths:
  /accesstoken:
    post:
      operationId: getAccessToken
      tags:
        - Create Access Token
      summary: Create a bearer access token.
      description: 'Using your app credentials, send a request to create a bearer access token that can be used to execute subsequent API actions. The actions  that the token can execute are determined by the permissions the app has.'
      parameters:
        - in: header
          name: Content-type
          description: Format of the message.
          required: true
          schema:
            description: Indicates the format of the message.
            type: string
            default: application/json
        - in: header
          name: X-GP-Version
          required: true
          schema:
            description: Indicates the version of the GP-API for this message.
            type: string
            default: '2021-03-22'
            minLength: 1
            maxLength: 50
        - schema:
            type: string
          in: header
          name: Prefer
          description: Not a Production Header used in API Design to trigger production like scenarios
      requestBody:
        content:
          application/json:
            schema:
              required:
                - app_id
                - grant_type
                - nonce
                - secret
              type: object
              properties:
                app_id:
                  type: string
                  description: The id of the app that was used to create the token.
                  example: U1lRHKomEn7DN907RCDPxVhyMfiMLcfy
                  minLength: 1
                  maxLength: 50
                nonce:
                  type: string
                  description: A unique random value included while creating the secret.
                  example: random_string
                  minLength: 1
                  maxLength: 50
                secret:
                  type: string
                  description: A unique string created using the nonce and app-key. This value is used to further authenticate the request. Created as follows - SHA512(NONCE.APP-KEY).
                  example: e776ce1d9e94d5072ee132258e446cd92668d7c28b2e475a345319b475ba601956c16e3983926ce279db6301d78b7f47cfb729e41b4169814e373f0a0bf38716
                  minLength: 1
                  maxLength: 128
                grant_type:
                  type: string
                  description: Indicates the type of access being requested.
                  enum:
                    - client_credentials
                  example: client_credentials
                seconds_to_expire:
                  type: integer
                  description: The time left in seconds before the token expires.
                  maximum: 604799
                  example: 604799
                interval_to_expire:
                  type: string
                  description: The time interval set for when the token will expire.
                  enum:
                    - WEEK
                    - DAY
                    - 12_HOURS
                    - 6_HOURS
                    - 3_HOURS
                    - 1_HOUR
                    - 30_MINUTES
                    - 10_MINUTES
                    - 5_MINUTES
                permissions:
                  type: array
                  items:
                    type: string
                    description: The list of the permissions the access token has or will have once created. This indicates the scope of authority a specific access token has.
                    example: TRN_POST_Authorize
            examples:
              Get Access Token:
                value:
                  app_id: i9R0byBBor6RqTQNj3g4MuVBwH5rd7yR
                  nonce: random_string
                  secret: e776ce1d9e94d5072ee132258e446cd92668d7c28b2e475a345319b475ba601956c16e3983926ce279db6301d78b7f47cfb729e41b4169814e373f0a0bf38716
                  grant_type: client_credentials
              Get Access Token - Set Permissions:
                value:
                  app_id: i9R0byBBor6RqTQNj3g4MuVBwH5rd7yR
                  nonce: random_string
                  secret: e776ce1d9e94d5072ee132258e446cd92668d7c28b2e475a345319b475ba601956c16e3983926ce279db6301d78b7f47cfb729e41b4169814e373f0a0bf38716
                  grant_type: client_credentials
                  seconds_to_expire: 6400
                  permissions:
                    - TRN_POST_Authorize
              TestyMacTestface:
                value:
                  app_id: U1lRHKomEn7DasdfsadfhyMfiMLcfy
                  nonce: rasdfasdfing
                  secret: sadfsadf
                  grant_type: client_credentials
                  permissions:
                    - TRN_POST_Authorize
                    - TRN_POST_Capture
        required: true
        description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The id of the app that was used to create the token.
                    example: U1lRHKomEn7DN907RCDPxVhyMfiMLcfy
                    minLength: 1
                    maxLength: 50
                  name:
                    type: string
                    description: This is a label to identify the merchant
                    example: '{{$randomUserName}}'
                  secret:
                    type: string
                    description: A unique string created using the nonce and app-key. This value is used to further authenticate the request. Created as follows - SHA512(NONCE.APP-KEY).
                    example: e776ce1d9e94d5072ee132258e446cd92668d7c28b2e475a345319b475ba601956c16e3983926ce279db6301d78b7f47cfb729e41b4169814e373f0a0bf38716
                    minLength: 1
                    maxLength: 128
              examples:
                cat:
                  summary: An example of a cat
                  value:
                    id: '2'
                    name: Fluffy
                    secret: sdfsadfsdfdfgdfgdsfg
                dog:
                  summary: An example of a dog
                  value:
                    id: '1'
                    name: Spot
                    secret: sdfsadfsdfdfgdfgdsfg
                example-1:
                  value:
                    id: U1lRHKomEn7DN907RCDPxVhyMfiMLcfy
                    name: '{{$randomUserName}}'
                    secret: e776ce1d9e94d5072ee132258e446cd92668d7c2
                example-5:
                  value:
                    id: U1lRHKomEn7DN907RCDPxVhyMfiMLcfy
                TestyMacTestface:
                  value:
                    id: TestyMacTestface
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: string
          description: The id of the app that was used to create the token.
          example: U1lRHKomEn7DN907RCDPxVhyMfiMLcfy
          minLength: 1
          maxLength: 50
        name:
          type: string
          description: This is a label to identify the merchant
          example: '{{$randomUserName}}'
        secret:
          type: string
          description: A unique string created using the nonce and app-key. This value is used to further authenticate the request. Created as follows - SHA512(NONCE.APP-KEY).
          example: e776ce1d9e94d5072ee132258e446cd92668d7c28b2e475a345319b475ba601956c16e3983926ce279db6301d78b7f47cfb729e41b4169814e373f0a0bf38716
          minLength: 1
          maxLength: 128
    request:
      required:
        - app_id
        - grant_type
        - nonce
        - secret
      type: object
      properties:
        app_id:
          type: string
          description: The id of the app that was used to create the token.
          example: U1lRHKomEn7DN907RCDPxVhyMfiMLcfy
          minLength: 1
          maxLength: 50
        nonce:
          type: string
          description: A unique random value included while creating the secret.
          example: random_string
          minLength: 1
          maxLength: 50
        secret:
          type: string
          description: A unique string created using the nonce and app-key. This value is used to further authenticate the request. Created as follows - SHA512(NONCE.APP-KEY).
          example: e776ce1d9e94d5072ee132258e446cd92668d7c28b2e475a345319b475ba601956c16e3983926ce279db6301d78b7f47cfb729e41b4169814e373f0a0bf38716
          minLength: 1
          maxLength: 128
        grant_type:
          type: string
          description: Indicates the type of access being requested.
          enum:
            - client_credentials
          example: client_credentials
        seconds_to_expire:
          type: integer
          description: The time left in seconds before the token expires.
          maximum: 604799
          example: 604799
        interval_to_expire:
          type: string
          description: The time interval set for when the token will expire.
          enum:
            - WEEK
            - DAY
            - 12_HOURS
            - 6_HOURS
            - 3_HOURS
            - 1_HOUR
            - 30_MINUTES
            - 10_MINUTES
            - 5_MINUTES
        permissions:
          type: array
          items:
            type: string
            description: The list of the permissions the access token has or will have once created. This indicates the scope of authority a specific access token has.
            example: TRN_POST_Authorize
    scope:
      type: object
      properties:
        merchant_id:
          type: string
          description: A unique identifier for the merchant set by Global Payments.
          example: MER_c4c0df11039c48a9b63701adeaa296c3
          minLength: 1
          maxLength: 50
        merchant_name:
          type: string
          description: A meaningful label for the merchant set by Global Payments.
          example: Sandbox_merchant_2
          minLength: 1
          maxLength: 50
        accounts:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: A unique identifier for the merchant account set by Global Payments.
                example: TRA_6716058969854a48b33347043ff8225f
                minLength: 1
                maxLength: 50
              name:
                type: string
                description: A meaningful label for the merchant account set by Global Payments.
                example: Transaction_Processing
                minLength: 1
                maxLength: 50
              permissions:
                type: array
                items:
                  type: array
                  items:
                    type: string
                    description: The list of the permissions the access token has or will have once created. This indicates the scope of authority a specific access token has.
                    example: TRN_POST_Authorize
    accounts:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            description: A unique identifier for the merchant account set by Global Payments.
            example: TRA_6716058969854a48b33347043ff8225f
            minLength: 1
            maxLength: 50
          name:
            type: string
            description: A meaningful label for the merchant account set by Global Payments.
            example: Transaction_Processing
            minLength: 1
            maxLength: 50
          permissions:
            type: array
            items:
              type: array
              items:
                type: string
                description: The list of the permissions the access token has or will have once created. This indicates the scope of authority a specific access token has.
                example: TRN_POST_Authorize
